version: "3.4"
services:
  app:
    container_name: onlinefood-app
    image: coderf003/onlinefood-app
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - ACCESS_TOKEN_KEY2=${ACCESS_TOKEN_KEY2}
      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
      - ACCESS_TOKEN_TIME=${ACCESS_TOKEN_TIME}
      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
      - REFRESH_TOKEN_TIME=${REFRESH_TOKEN_TIME}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - MAILDEV_USER=${MAILDEV_USER}
      - MAILDEV_PASS=${MAILDEV_PASS}
      - API_HOST=${API_HOST}
      - TOP_SECRET=${TOP_SECRET}

  mongo:
    container_name: my-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
